# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: velocity.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='velocity.proto',
  package='velocity',
  serialized_pb='\n\x0evelocity.proto\x12\x08velocity\")\n\x06VelMsg\x12\x0e\n\x06linear\x18\x01 \x02(\x01\x12\x0f\n\x07\x61ngular\x18\x02 \x02(\x01')




_VELMSG = _descriptor.Descriptor(
  name='VelMsg',
  full_name='velocity.VelMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear', full_name='velocity.VelMsg.linear', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angular', full_name='velocity.VelMsg.angular', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['VelMsg'] = _VELMSG

class VelMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VELMSG

  # @@protoc_insertion_point(class_scope:velocity.VelMsg)


# @@protoc_insertion_point(module_scope)
