# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_SERVICEREQUEST_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='LtlmopCsharpMessages.ServiceRequest.Type',
  filename='Type',
  values=[
    descriptor.EnumValueDescriptor(
      name='VELOCITY_CONTROL', index=0, number=0,
      options=None,
      type=None),
  ],
  options=None,
)


_SERVICEREQUEST = descriptor.Descriptor(
  name='ServiceRequest',
  full_name='LtlmopCsharpMessages.ServiceRequest',
  filename='LtlmopCsharpMessages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='LtlmopCsharpMessages.ServiceRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _SERVICEREQUEST_TYPE,
  ],
  options=None)


_VELOCITYMESSAGE = descriptor.Descriptor(
  name='VelocityMessage',
  full_name='LtlmopCsharpMessages.VelocityMessage',
  filename='LtlmopCsharpMessages.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='linear', full_name='LtlmopCsharpMessages.VelocityMessage.linear', index=0,
      number=1, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='angular', full_name='LtlmopCsharpMessages.VelocityMessage.angular', index=1,
      number=2, type=1, cpp_type=5, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SERVICEREQUEST.fields_by_name['type'].enum_type = _SERVICEREQUEST_TYPE

class ServiceRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVICEREQUEST

class VelocityMessage(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VELOCITYMESSAGE

